<a href="https://colab.research.google.com/github/vinoimaya07-svg/FDS-LAB/blob/main/163Exercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Array Creation
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Original Array:")
print(data)

# 2. Reshaping
reshaped = data.reshape(1, 9)

print("\nReshaped Array:")
print(reshaped)

# 3. Indexing
print("\nElement at row 2, column 3:")
print(data[1, 2])

# 4. Slicing
print("\nFirst two rows:")
print(data[:2])

# 5. Aggregation
print("\nSum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))

# 6. Min-Max Normalization
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))

print("\nNormalized Array:")
print(np.round(normalized, 2))

# 7. Standardization
standardized = (data - np.mean(data)) / np.std(data)

print("\nStandardized Array:")
print(np.round(standardized, 2))

# 8. Boolean Masking
mask = data > 50

print("\nBoolean Mask:")
print(mask)

# 9. Boolean Filtering
filtered = data[data > 50]

print("\nValues Greater Than 50:")
print(filtered)

# 10. Handling Missing Values
data_with_nan = np.array([10, 20, np.nan, 40, 50])

print("\nArray With Missing Value:")
print(data_with_nan)

mean_value = np.nanmean(data_with_nan)
data_with_nan[np.isnan(data_with_nan)] = mean_value

print("After Handling Missing Value:")
print(data_with_nan)

# 11. Sorting
unsorted = np.array([50, 20, 90, 10, 40])

print("\nSorted Array:")
print(np.sort(unsorted))

# 12. Concatenation
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenated = np.concatenate((array1, array2))

print("\nConcatenated Array:")
print(concatenated)

# 13. Transformation
transformed = data * 2 + 5

print("\nTransformed Multidimensional Array:")
print(transformed)

Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Reshaped Array:
[[10 20 30 40 50 60 70 80 90]]

Element at row 2, column 3:
60

First two rows:
[[10 20 30]
 [40 50 60]]

Sum: 450
Mean: 50.0
Minimum: 10
Maximum: 90

Normalized Array:
[[0.   0.12 0.25]
 [0.38 0.5  0.62]
 [0.75 0.88 1.  ]]

Standardized Array:
[[-1.55 -1.16 -0.77]
 [-0.39  0.    0.39]
 [ 0.77  1.16  1.55]]

Boolean Mask:
[[False False False]
 [False False  True]
 [ True  True  True]]

Values Greater Than 50:
[60 70 80 90]

Array With Missing Value:
[10. 20. nan 40. 50.]
After Handling Missing Value:
[10. 20. 30. 40. 50.]

Sorted Array:
[10 20 40 50 90]

Concatenated Array:
[1 2 3 4 5 6]

Transformed Multidimensional Array:
[[ 25  45  65]
 [ 85 105 125]
 [145 165 185]]
